[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "22.13.0"   # or newer 22.x LTS
  NPM_FLAGS = "--legacy-peer-deps"  # optional; only if your install needs it


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
